<?php

/**
 * Cron entry for the Encoder monitor (install/cron.php), built from the real installation folder
 * because the Encoder can live anywhere and several Encoders can share a server.
 *
 * Dependency-free on purpose: install/installCron.php runs as root and must not load the Encoder
 * configuration, which could create root-owned log or session files the web server cannot use.
 */
class EncoderCron
{
    // Same search path a web server has, so run.php started by the cron finds yt-dlp, node and
    // ffmpeg in /usr/local/bin; cron only sets /usr/bin:/bin.
    const PATH = '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin';

    public static function getFileName($rootPath)
    {
        return 'avideo-encoder-' . substr(md5(self::normalizeRoot($rootPath)), 0, 8);
    }

    // POSIX quoting (cron runs commands with /bin/sh), independent of the OS running PHP.
    public static function shellQuote($value)
    {
        return "'" . str_replace("'", "'\\''", (string) $value) . "'";
    }

    public static function getCommand($rootPath, $php)
    {
        $command = self::shellQuote($php) . ' ' . self::shellQuote(self::normalizeRoot($rootPath) . 'install/cron.php');
        // cron turns an unescaped % into a newline, even inside quotes.
        return 'PATH=' . self::PATH . ' ' . str_replace('%', '\\%', $command) . ' > /dev/null 2>&1';
    }

    // Content of /etc/cron.d/<getFileName()>, which needs the user column.
    public static function buildFile($rootPath, $php, $user)
    {
        return '# AVideo Encoder monitor for ' . self::normalizeRoot($rootPath) . " (generated by install/installCron.php)\n"
            . "SHELL=/bin/sh\n"
            . '* * * * * ' . $user . ' ' . self::getCommand($rootPath, $php) . "\n";
    }

    private static function normalizeRoot($rootPath)
    {
        return rtrim(str_replace('\\', '/', (string) $rootPath), '/') . '/';
    }
}
