name: Validate/Lint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.1', '8.2', '8.3']
    name: PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: pcre, mbstring, xml, curl, gd, pdo_mysql, zip, intl

      - name: Lint
        run: |
          lintPaths=()
          lintPaths+=("${GITHUB_WORKSPACE}/API")
          lintPaths+=("${GITHUB_WORKSPACE}/deploy")
          lintPaths+=("${GITHUB_WORKSPACE}/install")
          lintPaths+=("${GITHUB_WORKSPACE}/locale")
          lintPaths+=("${GITHUB_WORKSPACE}/objects")
          lintPaths+=("${GITHUB_WORKSPACE}/update")
          lintPaths+=("${GITHUB_WORKSPACE}/view")
          lintPaths+=("${GITHUB_WORKSPACE}/videos")
          # Lint root PHP files
          for file in "${GITHUB_WORKSPACE}"/*.php; do
            [ -f "$file" ] || continue
            RESULTS=$(php -l "$file")
            if [ "$RESULTS" != "No syntax errors detected in $file" ]; then
              echo "$RESULTS"
            fi
          done
          for lintPath in "${lintPaths[@]}"; do
            for file in $(find "$lintPath" -name "*.php" -o -name "*.phtml"); do
              RESULTS=$(php -l "$file")
              if [ "$RESULTS" != "No syntax errors detected in $file" ]; then
                echo "$RESULTS"
              fi
            done
          done
